// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd6a4VACLnUp2YfLnhoXgHq92p8D_1_tY',
    appId: '1:882362642630:web:70036d64ce2e6c537b67c7',
    messagingSenderId: '882362642630',
    projectId: 'chat-766d3',
    authDomain: 'chat-766d3.firebaseapp.com',
    storageBucket: 'chat-766d3.firebasestorage.app',
    measurementId: 'G-C05LQSME3X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCweQT9PDIuuFIfqxLCNCGthOggJpOzfOQ',
    appId: '1:882362642630:android:a58b5ce13f77ed797b67c7',
    messagingSenderId: '882362642630',
    projectId: 'chat-766d3',
    storageBucket: 'chat-766d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj7WyTiFGfUMjeGtZNGHWuLGCo4znB59M',
    appId: '1:882362642630:ios:452ddbd2b2ee55667b67c7',
    messagingSenderId: '882362642630',
    projectId: 'chat-766d3',
    storageBucket: 'chat-766d3.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAj7WyTiFGfUMjeGtZNGHWuLGCo4znB59M',
    appId: '1:882362642630:ios:452ddbd2b2ee55667b67c7',
    messagingSenderId: '882362642630',
    projectId: 'chat-766d3',
    storageBucket: 'chat-766d3.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAy7i37tzQc4NdSrwtPVBW3iQIXgZiPU5g',
    appId: '1:882362642630:web:b624acc827455c017b67c7',
    messagingSenderId: '882362642630',
    projectId: 'chat-766d3',
    authDomain: 'chat-766d3.firebaseapp.com',
    storageBucket: 'chat-766d3.firebasestorage.app',
    measurementId: 'G-VQ5NDW6DQ9',
  );
}
